export enum HttpStatus {
  Continue = 100,
  SwitchingProtocols = 101,
  Processing = 102,
  OK = 200,
  Created = 201,
  Accepted = 202,
  NonAuthoritativeInformation = 203,
  NoContent = 204,
  ResetContent = 205,
  PartialContent = 206,
  MultiStatus = 207,
  MultipleChoices = 300,
  MovedPermanently = 301,
  MovedTemporarily = 302,
  SeeOther = 303,
  NotModified = 304,
  UseProxy = 305,
  TemporaryRedirect = 307,
  BadRequest = 400,
  Unauthorized = 401,
  PaymentRequired = 402,
  Forbidden = 403,
  NotFound = 404,
  MethodNotAllowed = 405,
  NotAcceptable = 406,
  ProxyAuthenticationRequired = 407,
  RequestTimeout = 408,
  Conflict = 409,
  Gone = 410,
  LengthRequired = 411,
  PreconditionFailed = 412,
  RequestEntityTooLarge = 413,
  RequestURITooLarge = 414,
  UnsupportedMediaType = 415,
  RequestedRangeNotSatisfiable = 416,
  ExpectationFailed = 417,
  ImATeapot = 418,
  UnprocessableEntity = 422,
  Locked = 423,
  FailedDependency = 424,
  TooEarly = 425,
  UpgradeRequired = 426,
  PreconditionRequired = 428,
  TooManyRequests = 429,
  RequestHeaderFieldsTooLarge = 431,
  UnavailableForLegalReasons = 451,
  InternalServerError = 500,
  NotImplemented = 501,
  BadGateway = 502,
  ServiceUnavailable = 503,
  GatewayTimeout = 504,
  HTTPVersionNotSupported = 505,
  VariantAlsoNegotiates = 506,
  InsufficientStorage = 507,
  BandwidthLimitExceeded = 509,
  NotExtended = 510,
  NetworkAuthenticationRequired = 511,
}

export const errorCodes = new Map([
  [HttpStatus.Continue, 'Continue'],
  [HttpStatus.SwitchingProtocols, 'Switching Protocols'],
  [HttpStatus.Processing, 'Processing'],
  [HttpStatus.OK, 'OK'],
  [HttpStatus.Created, 'Created'],
  [HttpStatus.Accepted, 'Accepted'],
  [HttpStatus.NonAuthoritativeInformation, 'Non-Authoritative Information'],
  [HttpStatus.NoContent, 'No Content'],
  [HttpStatus.ResetContent, 'Reset Content'],
  [HttpStatus.PartialContent, 'Partial Content'],
  [HttpStatus.MultiStatus, 'Multi-Status'],
  [HttpStatus.MultipleChoices, 'Multiple Choices'],
  [HttpStatus.MovedPermanently, 'Moved Permanently'],
  [HttpStatus.MovedTemporarily, 'Moved Temporarily'],
  [HttpStatus.SeeOther, 'See Other'],
  [HttpStatus.NotModified, 'Not Modified'],
  [HttpStatus.UseProxy, 'Use Proxy'],
  [HttpStatus.TemporaryRedirect, 'Temporary Redirect'],
  [HttpStatus.BadRequest, 'Bad Request'],
  [HttpStatus.Unauthorized, 'Unauthorized'],
  [HttpStatus.PaymentRequired, 'Payment Required'],
  [HttpStatus.Forbidden, 'Forbidden'],
  [HttpStatus.NotFound, 'Not Found'],
  [HttpStatus.MethodNotAllowed, 'Method Not Allowed'],
  [HttpStatus.NotAcceptable, 'Not Acceptable'],
  [HttpStatus.ProxyAuthenticationRequired, 'Proxy Authentication Required'],
  [HttpStatus.RequestTimeout, 'Request Time-out'],
  [HttpStatus.Conflict, 'Conflict'],
  [HttpStatus.Gone, 'Gone'],
  [HttpStatus.LengthRequired, 'Length Required'],
  [HttpStatus.PreconditionFailed, 'Precondition Failed'],
  [HttpStatus.RequestEntityTooLarge, 'Request Entity Too Large'],
  [HttpStatus.RequestURITooLarge, 'Request-URI Too Large'],
  [HttpStatus.UnsupportedMediaType, 'Unsupported Media Type'],
  [HttpStatus.RequestedRangeNotSatisfiable, 'Requested Range Not Satisfiable'],
  [HttpStatus.ExpectationFailed, 'Expectation Failed'],
  [HttpStatus.ImATeapot, "I'm a teapot"],
  [HttpStatus.UnprocessableEntity, 'Unprocessable Entity'],
  [HttpStatus.Locked, 'Locked'],
  [HttpStatus.FailedDependency, 'Failed Dependency'],
  [HttpStatus.TooEarly, 'Too Early'],
  [HttpStatus.UpgradeRequired, 'Upgrade Required'],
  [HttpStatus.PreconditionRequired, 'Precondition Required'],
  [HttpStatus.TooManyRequests, 'Too Many Requests'],
  [HttpStatus.RequestHeaderFieldsTooLarge, 'Request Header Fields Too Large'],
  [HttpStatus.UnavailableForLegalReasons, 'Unavailable For Legal Reasons'],
  [HttpStatus.InternalServerError, 'Internal Server Error'],
  [HttpStatus.NotImplemented, 'Not Implemented'],
  [HttpStatus.BadGateway, 'Bad Gateway'],
  [HttpStatus.ServiceUnavailable, 'Service Unavailable'],
  [HttpStatus.GatewayTimeout, 'Gateway Time-out'],
  [HttpStatus.HTTPVersionNotSupported, 'HTTP Version Not Supported'],
  [HttpStatus.VariantAlsoNegotiates, 'Variant Also Negotiates'],
  [HttpStatus.InsufficientStorage, 'Insufficient Storage'],
  [HttpStatus.BandwidthLimitExceeded, 'Bandwidth Limit Exceeded'],
  [HttpStatus.NotExtended, 'Not Extended'],
  [HttpStatus.NetworkAuthenticationRequired, 'Network Authentication Required'],
]);
